language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
sudo: required
# command to install dependencies
install:
  - "pip install -i requirements.txt"
  - "pip install pytest"
  - "pip install pylint"
# command to run tests
script:
  - pytest
  - pylint drip/
